apiVersion: v1
kind: Service
metadata:
  name: blog-feedback-service-service
spec:
  selector:
    app: blog-feedback-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
